### ISSUE TITLE
Feature Request:  New Content and Movie Name

### ISSUE THREAD

**Issue by tisserda** [ch491/udi-plex-poly#1]
Been using this Poly for a couple of weeks and it works great!
Have kids at home, I can see how the rapid-trigger would be valuable and you implemented a neat way to solve it.

2 Feature requests if possible:
1.  Can you capture and feed the new Content events?  I was thinking of using the ISY to text all the users on the Plex server when new movies get added.
2.  Can you feed the movie name along with the play/pause/stop event?

**Comment by ch491** [comment]
> Been using this Poly for a couple of weeks and it works great!
> Have kids at home, I can see how the rapid-trigger would be valuable and you implemented a neat way to solve it.
> 
> 2 Feature requests if possible:
> 
> 1. Can you capture and feed the new Content events?  I was thinking of using the ISY to text all the users on the Plex server when new movies get added.
> 2. Can you feed the movie name along with the play/pause/stop event?

I am so glad you are enjoying it!
I am deep in work right now (College Professor) but around the Holiday I should have time to work on version 2. 

Version 2 (ideas in the queue):
- Add Movie or TV Show Titles (This is a trick as ISY does not support strings "alpha characters")
- See if it is possible to have the ISY control the client (i.e. STOP if content-rating is too high, etc.)
- I can add new Content events, to the list 

Thank you for the feedback and patience as version 2 will not be out till 2021.
