### ISSUE TITLE
Available in Polyglot v3?

### ISSUE THREAD

**Issue by bleepblorp** [ch491/udi-plex-poly#3]
Hello ch491,
I have been using your node server without issue on Polyglot v2. Huge Plex fan so I really appreciate you making this integration!

I am wondering about v3 support. It isn't clear to me what UDI plans for v2, but it seems it might not work forever - the forum shows it as deprecated as I look at it today. I have no reason to move to v3 at this point as everything is working great, but just curious if you are planning on adding to the v3 store.

Best regards,
Bertram

**Comment by ch491** [comment]
Hey there. So glad to hear it is working great under v2. It was ported by an admin to v3 I will be checking it (for bugs) this week. If you do not hear from me then it is good to go for PGv3. 

Note: I was a PG2 guy but moved to PG3/IoP this month and it is nice 👌 

Thank you for using,
Chad

**Comment by ch491** [comment]
Hey there. So glad to hear it is working great under v2. It was ported by an admin to v3 I will be checking it (for bugs) this week. If you do not hear from me then it is good to go for PGv3. Note: I was a PG2 guy but moved to PG3/IoP this month and it is nice 👌 Thank you for using,ChadSent from my Galaxy
-------- Original message --------From: bleepblorp ***@***.***> Date: 2022-05-10  2:59 p.m.  (GMT-05:00) To: ch491/udi-plex-poly ***@***.***> Cc: Subscribed ***@***.***> Subject: [ch491/udi-plex-poly] Available in Polyglot v3? (Issue #3) 
Hello ch491,
I have been using your node server without issue on Polyglot v2. Huge Plex fan so I really appreciate you making this integration!
I am wondering about v3 support. It isn't clear to me what UDI plans for v2, but it seems it might not work forever - the forum shows it as deprecated as I look at it today. I have no reason to move to v3 at this point as everything is working great, but just curious if you are planning on adding to the v3 store.
Best regards,
Bertram
